sudo: no
language: python
python: '2.7'

env:
  - TEST_SUITE=lint
  - TEST_SUITE=test

cache:
  directories:
    - pip_cache

install:
  - 'pip install -e requirements.txt'

script:
  - ./tests/dispatch.sh $TEST_SUITE

notifications:
  irc:
    channels:
      - "irc.freenode.org#richard"
    on_success: change
    on_failure: always
